# (c) https://github.com/MontiCore/monticore

image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:6.8.2-jdk11

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
    - .gradle/wrapper
  key: ${CI_COMMIT_REF_SLUG}

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - deploy
  - check
  - mirror

build:
  stage: build
  script:
    - "gradle assemble --refresh-dependencies $GRADLE_OPTS $ARGS1"
  artifacts:
    paths:
      - "."
    expire_in: 1 week
#  except:
#    changes:
#    - .gitignore
#    - README.md
#    - .gitlab-ci.yml

test:
  stage: test
  dependencies:
    - build
  script:
    - "gradle check $GRADLE_OPTS $ARGS2"
#  except:
#    changes:
#    - .gitignore
#    - README.md
#    - .gitlab-ci.yml